### ISSUE TITLE
Parliamentary debates from 1854 until 1987

### ISSUE THREAD

**Issue by mubashirqasim** [TeHikuMedia/nga-tautohetohe#7]
Hi there,

Great piece of work. I also need to download parliamentary debates from 1854 until 1987 from HathiTrust. I wonder if you still have those pdfs sitting somewhere on your dropbox; google drive etc.

If yes, could you please kindly share those with me.

Many thanks,

Mubashir

**Comment by niusealeo** [comment]
Hi Mubashir
I have CSVs of the raw OCR scans?

**Comment by niusealeo** [comment]
Here you go, a link to onedrive folder :)
All 484 files should be uploaded in a few minutes
https://1drv.ms/f/s!AutNgpEydmJiig1laQ2-SSoCDlyG

**Comment by mubashirqasim** [comment]
Hi Will,

This is really an excellent help for my final PhD paper :)
I would explicitly acknowledge this with a reference to your github repo. 
Also happy to reference any of your work if you wish.

Cordial thanks for your support once again.

Best regards,

M
